package java.org.example.db.dao;

import java.sql.ResultSet;
import java.sql.SQLException;

import java.org.example.db.HsqlUnitOfWork;
import java.org.example.magazyn.Towar;

public class HsqlTowarDao extends HsqlDaoBase<Towar> implements TowarDao{

	
	public HsqlTowarDao(HsqlUnitOfWork uow) {
		super(uow);
	}


	@Override
	protected void setUpdateQuery(Towar ent) throws SQLException {

		update.setString(1, ent.getKod());
		update.setString(2, ent.getNazwa());
		update.setDouble(3, ent.getCena());
		update.setInt(4, ent.getId());
		
	}

	@Override
	protected Towar build(ResultSet rs) throws SQLException {

		Towar t = new Towar();
		t.setKod(rs.getString("kod"));
		t.setNazwa(rs.getString("nazwa"));
		t.setCena(rs.getDouble("cena"));
		t.setId(rs.getInt("id"));
		return t;
	}

	@Override
	protected void setInsertQuery(Towar ent) throws SQLException {
		insert.setString(1, ent.getKod());
		insert.setString(2, ent.getNazwa());	
		insert.setDouble(3, ent.getCena());
		
	}

	@Override
	protected String getTableName() {
		return "towar";
	}

	@Override
	protected String getCreateQuery() {
		return "CREATE TABLE towar("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "kod VARCHAR(50),"
				+ "nazwa VARCHAR(50),"
				+ "cena DOUBLE(15,2)"
				+ ")";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into towar(kod,nazwa,cena) values (?,?,?)";
	}

	@Override
	protected String getUpdateQuery() {
		return "update towar set"
				+ "(kod,nazwa,cena)=(?,?,?)"
				+ "where id=?";
	}


	public void setStany(Towar t) {
		// TODO Auto-generated method stub
		
	}




	
	
	

}
