package org.example.db.dao;

import java.sql.ResultSet;
import java.sql.SQLException;

import org.example.db.HsqlUnitOfWork;
import org.example.magazyn.Magazyn;

public class HsqlMagazynDao extends HsqlDaoBase<Magazyn> implements MagazynDao{

	
	public HsqlMagazynDao(HsqlUnitOfWork uow) {
		super(uow);
	}


	@Override
	protected void setUpdateQuery(Magazyn ent) throws SQLException {

		update.setString(1, ent.getKod());
		update.setString(2, ent.getNazwa());
		update.setInt(3, ent.getId());
		
	}

	@Override
	protected Magazyn build(ResultSet rs) throws SQLException {

		Magazyn m = new Magazyn();
		m.setKod(rs.getString("kod"));
		m.setNazwa(rs.getString("nazwa"));
		m.setId(rs.getInt("id"));
		return m;
	}

	@Override
	protected void setInsertQuery(Magazyn ent) throws SQLException {
		insert.setString(1, ent.getKod());
		insert.setString(2, ent.getNazwa());		
		
	}

	@Override
	protected String getTableName() {
		return "magazyn";
	}

	@Override
	protected String getCreateQuery() {
		return "CREATE TABLE magazyn("
				+ "id bigint GENERATED BY DEFAULT AS IDENTITY,"
				+ "kod VARCHAR(50),"
				+ "nazwa VARCHAR(50)"
				+ ")";
	}

	@Override
	protected String getInsertQuery() {
		return "insert into magazyn(kod,nazwa) values (?,?)";
	}

	@Override
	protected String getUpdateQuery() {
		return "update magazyn set"
				+ "(kod,nazwa)=(?,?)"
				+ "where id=?";
	}


	public void setStany(Magazyn m) {
		
	}

	
	
	

}
